### ISSUE TITLE
When using a vstemplate to expose .net core templates, options are not shown

### ISSUE THREAD

**Issue by dotMorten** [dotnet/templates#438]
When you have a .net core template wrapping in a vsix as demonstrated in https://github.com/phenning/templateSamples, you don't get the options the template exposes. With the new v16.9 feature for showing .NET Core templates without the vsix, this becomes very clear.
If you pick the first option here:
![image](https://user-images.githubusercontent.com/1378165/109426122-ada60900-79a0-11eb-81b0-9d824f328386.png)
You'll be met with this dialog:
![image](https://user-images.githubusercontent.com/1378165/109426365-3c675580-79a2-11eb-97f2-5d27960e0192.png)
However that dialog is skipped if you pick the second option.

You can use this fork of the templateSamples to test it out:
https://github.com/dotMorten/templateSamples/tree/AddTFM

/CC @phenning

**Comment by phenning** [comment]
@dotMorten This is by design actually, the vstemplate based model does not have the ability to use or surface any options on the additional information page. The additional information page is only accessible for .NET Core based templates via the preview feature. 

However, as part of the preview feature we do have an IVsFilterNewProjectDlg filter which should be filtering out any vstemplate files invoking the TemplateEngineWizard in order to remove duplicates entries. Looking at the code though, the filter only applies if there is an explict CustomParameter specified

`<CustomParameter Name="$uistyle$" Value="none"/>`

I'll update the sample to reflect this. Let me know if explicitly setting the custom parameter works for you. This is the same mechanism we use to hide the other vstemplate stubs for .NET Core templates which are shipped in Visual Studio.

**Comment by dotMorten** [comment]
@phenning Thanks! I'll add that to mine as well.

**Comment by sayedihashimi** [comment]
When we designed the core feature we didn't anticipate the importance of vsix containing templates. I'm now aware of several extensions that use this approach. It would be great to have a better story here. Next week I will discuss with Phil, and others, to see what all the options are. Ideally I'd like to be able to "discover" Template Engine templates when a vsix is installed. I haven't consulted anyone on this approach yet, so it may not be feasible. Once we discuss I will post an update here. I'd like to note that we are very busy with other work at the moment, so if we are able to come up with something, it will take time to implement. This likely will need updates from a few different teams, and that requires coordination, which lengthens the amount of time it takes to get anything done.

**Comment by jeromelaban** [comment]
I was not aware this was an option, though as far as Uno's templates are concerned, we're able to support more scenarios with "original" vsix templates, such as extended token to support spaces and dashes in project names, custom DTE post build actions and wizard extensions such as the certificate generator for UWP.

In order to support those vsix features, we're generating the "dotnet template" content from the vsix template by replacing tokens to what the templating engine expects.

Yet, it'd be a time saver to be able to use dotnet templates completely, particularly to get a proper experience on macOS and Linux, including getting options shown to the user where possible.

That being said, being able to bundle dotnet templates in a vsix has an ease-of-use aspect that is difficult to beat for VS users that are not particularly aware of CLI's dotnet new templates. Some more unification would be very welcome :)

**Comment by dotMorten** [comment]
@jeromelaban Yeah there's a few features missing. Personally my issue is I can't associate icons with the .NET Core templates. So I get this sort of terrible experience where the .net core based ones looks out of place:
![image](https://user-images.githubusercontent.com/1378165/109443916-bc1c1100-79f0-11eb-92b7-e5b858ae3356.png)

**Comment by phenning** [comment]
> @jeromelaban Yeah there's a few features missing. Personally my issue is I can't associate icons with the .NET Core templates. So I get this sort of terrible experience where the .net core based ones looks out of place:
> ![image](https://user-images.githubusercontent.com/1378165/109443916-bc1c1100-79f0-11eb-92b7-e5b858ae3356.png)

@dotMorten My templateSample repo was created before we had support for .NET Core templates available directly in the project dialog and has not been significantly updated.

We actually do have support for custom icons. I describe the process to get them hooked up here:

https://github.com/phenning/templateSamples/wiki/Including-an-icon

**Comment by phenning** [comment]
And to comment on one other thing. The current implementation can discover template engine templates which are shipped via VSIX. The samples repo provides steps on how to do this. What is no longer needed with the new Visual Studio experience is the step to include the vstemplate breadcrumb file. All the other steps for generating the template package itself as well as the VSIX are still valid though.

**Comment by sayedihashimi** [comment]
@dotMorten here are some docs you can take a loo at https://github.com/sayedihashimi/template-sample. There is also a template analyzer tool there.

**Comment by sayedihashimi** [comment]
@dotMorten have you got this working now? If so, I believe that we can close this issue.

**Comment by dotMorten** [comment]
@sayedihashimi  Yup. I already closed it on Feb 28 btw :)

**Comment by sayedihashimi** [comment]
@dotMorten sorry about that, not sure how I missed that you already closed this.
