### ISSUE TITLE
Enable nullable by default for new projects

### ISSUE THREAD

**Issue by mikadumont** [dotnet/templates#485]

**Comment by jmarolf** [comment]
@kendrahavens I am intentionally not enabling nullable for new test templates. Let me know if you think we _should_ enable nullable for new tests projects by default.

**Comment by richlander** [comment]
I like nullable and use it. I consider it to be an advanced feature. If we enable it by default, we need to validate that our documentation is up to the task to support people who are confused. It is guaranteed that people will get error messages that they don't understand once they starting coding. Also, we need to give people guidance on when to use the `!` operator. I've found that I only consistently use it in `Dispose` methods.

I'd want to see a list of pre-steps that we'd need to do BEFORE enabling nullable to feel comfortable about.

BTW: The docs may well be "up to the task". Major point is that this isn't a feature you just enable in templates and hope it works out. Nullable is a lot more complicated, IMO, than top-level statements, for example.

I can see that this issue is closed. I wanted to share my thoughts on this since this topic will likely come up again.

**Comment by jamesmontemagno** [comment]
To Rich's point I agree that we need to do some education and advocacy:

1. work with package owners to turn on nullable
2. update docs with why/how/what on nullable
3. create video describing why and how and what
4. create migration guide for package owners

If it creates better code and apps then I think it should be on by default and how we teach.

**Comment by cartermp** [comment]
Note that the context here is it would be one by default for _new_ projects only. Not existing ones. And there's no errors, only warnings (unless someone makes warnings errors, in which case they are already advanced users).

> Major point is that this isn't a feature you just enable in templates and hope it works out

@richlander could you clarify this? The feature has seen a bunch of improvements due to adoption by package authors and some advanced users, but we're pretty much now at the point where we just need more widespread usage. The safest route forward is to enable it for new projects, and at some point in the future, for _all_ projects. This would be that next step.

> work with package owners to turn on nullable

This has been ongoing, and lots of packages have done so already.

> update docs with why/how/what on nullable

We have docs here: https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references

There could perhaps be more on the _why_, but at the same time, the goal is that reference types distinguish between nullable/non-nullable moving forward. It's not some additional "advanced mode" to turn on. It's just what C# is about moving forward.

> create video describing why and how and what

Seems great, but I don't think this is needed for new projects right now.

> create migration guide for package owners

We don't have this, but all things nullable (e.g., the attributes package authors care about) are documented. I don't think this is a prerequisite for new projects though.

**Comment by richlander** [comment]
> Major point is that this isn't a feature you just enable in templates and hope it works out

All I meant is that we need a plan and documentation that covers basic questions. For example, do we need a new warning with `dotnet new` that says:

```
This project has nullable reference types enabled. For more information go to somelink.
```
